esphome:
  name: toug
  # on_boot:
    # - priority: 600
      # then:
          # - if:
              # condition:
                # and:
                  # - sensor.in_range:
                      # id: temperature_bas
                      # below: 59.0
                  # - sensor.in_range:
                      # id: temperature_haut
                      # below: 59.0
              # then:
                # - switch.turn_off: force_60
              # else:
                # - switch.turn_on: force_60
                
esp32:
  board: wt32-eth01

substitutions:
  api_key: !secret esphome_api_key

# wifi:
  # ssid: !secret wifi_ssid
  # password: !secret wifi_password

logger:
  id: component_logger
  # baud_rate: 0

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

web_server:
  port: 80
  local: true
  
ota:
  - platform: esphome  # Your existing OTA method
  - platform: web_server  # Add this for web-based OTA uploads
 
api:

i2c:
    sda: GPIO04
    scl: GPIO02
    frequency: 100kHz 
    
# pcf8574:
  # - id: 'pcf8574_hub'
    # address: 0x20
    # pcf8575: true

uart:
    - id: U0
      tx_pin: GPIO01
      rx_pin: GPIO03
      baud_rate: 115200
      parity: NONE
      stop_bits: 1
      rx_buffer_size : 512
      debug:
        direction: RX
        dummy_receiver: true
        after:
          # delimiter: "\n"
          timeout: 100ms 
        sequence:
          - lambda: |-
              static unsigned long previousMillis = 0;
              unsigned long currentMillis = millis();
              unsigned long elapsedTime = currentMillis - previousMillis;
              previousMillis = currentMillis;
              ESP_LOGD("custom", "Temps écoulé : %lu ms", elapsedTime);
          - lambda: UARTDebug::log_hex(direction, bytes, ':'); 

    - id: U1
      tx_pin: GPIO17
      rx_pin: GPIO05
      baud_rate: 19200
      parity: EVEN
      stop_bits: 1

    - id: U2
      tx_pin: GPIO14
      rx_pin: GPIO15
      baud_rate: 19200
      parity: EVEN
      stop_bits: 1

modbus:
    - id: modbus1
      uart_id: U1
    - id: modbus2
      uart_id: U2

modbus_controller:
    - address: 0x1
      id: modbus_user
      update_interval: 10s
      modbus_id: modbus1
    - address: 0x1
      id: modbus_telecommande
      update_interval: 10s
      modbus_id: modbus2

ads1115:
  - address: 0x48

binary_sensor:
  - platform: gpio
    name: "Bouche K1a"
    device_class: opening
    icon: "mdi:hvac"
    pin:
      number: GPIO39
      mode: INPUT
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
  - platform: gpio
    name: "Bouche K2"
    device_class: opening
    icon: "mdi:hvac"
    pin:
      number: GPIO35
      mode: INPUT
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
  - platform: gpio
    name: "Bouche K3"
    device_class: opening
    icon: "mdi:hvac"
    pin:
      number: GPIO36
      mode: INPUT
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
  - platform: gpio
    name: "Bouche K4"
    device_class: opening
    icon: "mdi:hvac"
    pin:
      number: GPIO12
      mode: INPUT
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
  - platform: gpio
    name: "Bouche K5"
    device_class: opening
    icon: "mdi:hvac"
    pin:
      number: GPIO33
      mode: INPUT
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
  - platform: gpio
    name: "Bouche K6"
    device_class: opening
    icon: "mdi:hvac"
    pin:
      number: GPIO32
      mode: INPUT
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
  # - platform: gpio
    # name: "Résistance appoint"
    # id: resistance_appoint
    # device_class: heat
    # pin:
      # number: GPIO32
      # mode: INPUT_PULLDOWN
      # inverted: False
    # filters:
      # - delayed_on: 1s
      # - delayed_off: 1s
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Filtre"
    icon: mdi:air-filter
    register_type: holding
    address: 0x0082
    device_class: problem

text_sensor:
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Aiguillage vanne"
    icon: mdi:valve
    entity_category: diagnostic
    register_type: holding
    address: 0x0064
    raw_encode: HEXBYTES
    lambda: |-
      uint16_t value = modbus_controller::word_from_hex_str(x, 0);
      switch (value) {
        case 0: return std::string("Etat initial");
        case 1: return std::string("ECS");
        case 2: return std::string("Air");
        case 3: return std::string("Standby");
        case 4: return std::string("Standby sécurité");
        case 5: return std::string("En cours de modification");
        default: return std::string("Unknown");
      }
      return x;
      
sensor:
  - platform: modbus_controller
    modbus_controller_id: modbus_telecommande
    name: "Pièce 1"         
    disabled_by_default: false 
    device_class: temperature
    state_class: measurement
    register_type: holding
    address: 190
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01 
  - platform: modbus_controller
    modbus_controller_id: modbus_telecommande
    name: "Pièce 2"
    disabled_by_default: false
    device_class: temperature
    state_class: measurement
    register_type: holding
    address: 192
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_telecommande
    name: "Pièce 3"
    disabled_by_default: false
    device_class: temperature
    state_class: measurement
    register_type: holding
    address: 193
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_telecommande
    name: "Pièce 4"
    disabled_by_default: false 
    device_class: temperature
    state_class: measurement
    register_type: holding
    address: 194
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_telecommande
    name: "Pièce 5"
    disabled_by_default: false 
    device_class: temperature
    state_class: measurement
    register_type: holding
    address: 195
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_telecommande
    name: "Pièce 6"
    disabled_by_default: false 
    device_class: temperature
    state_class: measurement
    register_type: holding
    address: 196
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Version logiciel régulateur"
    entity_category: diagnostic
    icon: mdi:package
    register_type: holding
    address: 0x0001
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Identifiant IHM"
    entity_category: diagnostic
    icon: mdi:identifier
    register_type: holding
    address: 0x000E
    value_type: U_DWORD
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Date et heure"
    device_class: timestamp
    entity_category: diagnostic
    icon: mdi:calendar-clock
    register_type: holding
    address: 0x0010
    value_type: U_DWORD
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Température pièce principale"
    entity_category: diagnostic
    device_class: "temperature"
    state_class: "measurement"
    icon: mdi:thermometer
    register_type: holding
    address: 0x0078
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Volume restant ECS"
    entity_category: diagnostic
    device_class: "volume"
    state_class: "measurement"
    icon: mdi:hydraulic-oil-level
    register_type: holding
    address: 0x006E
    value_type: U_WORD
    unit_of_measurement: "L"
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: consigne_ecs_lue
    register_type: holding
    address: 0x006F
    value_type: U_WORD
    accuracy_decimals: 1
    unit_of_measurement: "°C"
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Température ECS"
    state_class: "measurement"
    entity_category: diagnostic
    device_class: "temperature"
    icon: mdi:water-thermometer-outline
    register_type: holding
    address: 0x0070
    value_type: U_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: thermostat_1
    internal: yes
    register_type: holding
    address: 0x96
    value_type: U_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: thermostat_2
    register_type: holding
    address: 0x97
    value_type: U_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: thermostat_3
    register_type: holding
    address: 0x98
    value_type: U_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: thermostat_4
    register_type: holding
    address: 0x99
    value_type: U_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: thermostat_5
    register_type: holding
    address: 0x9A
    value_type: U_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: thermostat_6
    register_type: holding
    address: 0x9B
    value_type: U_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: thermostat_7
    register_type: holding
    address: 0x9C
    value_type: U_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: thermostat_8
    register_type: holding
    address: 0x9D
    value_type: U_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: thermostat_9
    register_type: holding
    address: 0x9E
    value_type: U_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: thermostat_10
    register_type: holding
    address: 0x9F
    value_type: U_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: hp
    register_type: holding
    address: 0xA0
    value_type: U_WORD
    unit_of_measurement: "€"
    accuracy_decimals: 4
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: hc
    register_type: holding
    address: 0xA1
    value_type: U_WORD
    unit_of_measurement: "€"
    accuracy_decimals: 4
    filters:
      - multiply: 0.001
  - platform: ntc
    sensor: resistance_bas
    calibration:
        - 1.3kOhm -> 78°C
        - 4.2kOhm -> 46°C
        - 11.66kOhm -> 24°C
    name: Temperature bas
    id: temperature_bas
    # on_value_range:
      # - below: 59.0
        # then:
          # - if:
              # condition:
                # sensor.in_range:
                  # id: temperature_haut
                  # below: 59.0
              # then:
                # - switch.turn_off: force_60
      # - above: 60.5
        # then:
          # - switch.turn_on: force_60
  - platform: resistance
    id: resistance_bas
    sensor: adc_bas
    configuration: DOWNSTREAM
    resistor: 10kOhm
    name: Resistance bas

    
  - platform: ntc
    sensor: resistance_haut
    calibration:
        - 1.3kOhm -> 78°C
        - 4.8kOhm -> 44°C
        - 11.42kOhm -> 24°C
    name: Temperature haut
    id: temperature_haut
    # on_value_range:
      # - below: 59.0
        # then:
          # - if:
              # condition:
                # sensor.in_range:
                  # id: temperature_bas
                  # below: 59.0
              # then:
                # - switch.turn_off: force_60
      # - above: 60.5
        # then:
          # - switch.turn_on: force_60
  - platform: resistance
    id: resistance_haut
    sensor: adc_haut
    configuration: DOWNSTREAM
    resistor: 10kOhm
    name: Resistance Haut

        
  - platform: ads1115
    id: adc_haut
    multiplexer: 'A0_GND'
    gain: 4.096
    update_interval: 10s
    filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 15
  - platform: ads1115
    id: adc_bas
    multiplexer: 'A1_GND'
    gain: 4.096
    update_interval: 10s
    filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 15

number:
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Consigne ECS"
    register_type: holding
    address: 0x006F
    value_type: U_WORD
    step: 0.1
    min_value: 7
    max_value: 61
    use_write_multiple: true
    entity_category: config
    unit_of_measurement: "°C"
    icon: "mdi:thermostat"
    multiply: 100
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Thermostat 1"
    icon: "mdi:thermostat"
    entity_category: config
    unit_of_measurement: "°C"
    address: 0x96
    value_type: U_WORD
    min_value: 0
    max_value: 31
    use_write_multiple: true
    multiply: 100
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Thermostat 2"
    icon: "mdi:thermostat"
    entity_category: config
    unit_of_measurement: "°C"
    address: 0x97
    value_type: U_WORD
    min_value: 0
    max_value: 31
    use_write_multiple: true
    multiply: 100
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Thermostat 3"
    icon: "mdi:thermostat"
    entity_category: config
    unit_of_measurement: "°C"
    address: 0x98
    value_type: U_WORD
    min_value: 0
    max_value: 31
    use_write_multiple: true
    multiply: 100
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Thermostat 4"
    icon: "mdi:thermostat"
    entity_category: config
    unit_of_measurement: "°C"
    address: 0x99
    value_type: U_WORD
    min_value: 0
    max_value: 31
    use_write_multiple: true
    multiply: 100
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Thermostat 5"
    icon: "mdi:thermostat"
    entity_category: config
    unit_of_measurement: "°C"
    address: 0x9A
    value_type: U_WORD
    min_value: 0
    max_value: 31
    use_write_multiple: true
    multiply: 100
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Thermostat 6"
    icon: "mdi:thermostat"
    entity_category: config
    unit_of_measurement: "°C"
    address: 0x9B
    value_type: U_WORD
    min_value: 0
    max_value: 31
    use_write_multiple: true
    multiply: 100
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Thermostat 7"
    icon: "mdi:thermostat"
    entity_category: config
    unit_of_measurement: "°C"
    address: 0x9C
    value_type: U_WORD
    min_value: 0
    max_value: 31
    use_write_multiple: true
    multiply: 100
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Thermostat 8"
    icon: "mdi:thermostat"
    entity_category: config
    unit_of_measurement: "°C"
    address: 0x9D
    value_type: U_WORD
    min_value: 0
    max_value: 31
    use_write_multiple: true
    multiply: 100
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Thermostat 9"
    icon: "mdi:thermostat"
    entity_category: config
    unit_of_measurement: "°C"
    address: 0x9E
    value_type: U_WORD
    min_value: 0
    max_value: 31
    use_write_multiple: true
    multiply: 100
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Thermostat 10"
    icon: "mdi:thermostat"
    entity_category: config
    unit_of_measurement: "°C"
    address: 0x9F
    value_type: U_WORD
    min_value: 0
    max_value: 31
    use_write_multiple: true
    multiply: 100
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Tarif HP"
    icon: mdi:currency-eur
    entity_category: config
    mode: box
    unit_of_measurement: "€"
    address: 0xA0
    value_type: U_WORD
    min_value: 0.05
    max_value: 1
    use_write_multiple: true
    multiply: 1000
    step: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Tarif HC"
    icon: mdi:currency-eur
    entity_category: config
    mode: box
    unit_of_measurement: "€"
    address: 0xA1
    value_type: U_WORD
    min_value: 0.05
    max_value: 1
    use_write_multiple: true
    multiply: 1000
    step: 0.001
    
select:
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Mode Air"
    icon: "mdi:air-conditioner"
    entity_category: config
    address: 0x007A
    value_type: U_WORD
    use_write_multiple: true
    optionsmap:
      "Off": 0
      "Confort Chauffage": 1
      "Eco Chauffage": 2
      "Prog A Chauffage": 3
      "Prog B Chauffage": 4
      "Confort Clim" : 5
      "Boost Clim" : 6
      "Prog C Clim" : 7
      "Prog D Clim" : 8
      "Ventilation" : 9
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    name: "Mode ECS"
    icon: "mdi:water-boiler"
    entity_category: config
    address: 0x0071
    value_type: U_WORD
    use_write_multiple: true
    optionsmap:
      "Off": 0
      "On": 1
      "Boost": 2
    
# switch:
  # - platform: gpio
    # id: force_60
    # #Relais
    # name: "Forçage 60°"
    # pin:
      # pcf8574: pcf8574_hub
      # number: 12
      # mode:
        # output: true
      # inverted: true
 
button:
  - platform: restart
    id: button_restart
    name: "Restart"
